# Generated by Django 4.1.9 on 2023-12-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=400)),
                ('tipo_evento', models.CharField(max_length=250)),
                ('lugar_evento', models.CharField(max_length=250)),
            ],
        ),
    ]
